services:
  paneld:
    build: .
    container_name: paneld
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - HOST_DATA_DIR=/home/david/code/Daemon/data
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - serverpanel
    restart: unless-stopped

networks:
  serverpanel:
    external: true